run:
  timeout: 5m
  go: "1.23"

linters-settings:
  goanalysis_metalinter:
    enabled: false  # ปิด linter ที่มีปัญหา

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - goanalysis_metalinter  # ปิด linter ที่มีปัญหา

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
