# ไฟล์นี้ถูกปรับปรุงให้อ่านค่า Environment Variables จากไฟล์ .env
# ทำให้การตั้งค่าง่ายและปลอดภัยขึ้น
services:
  postgres:
    image: postgres:16-alpine
    # ตั้งค่าสำหรับฐานข้อมูล โดยดึงค่ามาจากไฟล์ .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      # เก็บข้อมูลของ database ไว้แม้จะปิด container ไปแล้ว
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - minio_data:/data

  api:
    build: . # สั่งให้สร้าง image จาก Dockerfile ใน folder ปัจจุบัน
    # โหลด Environment Variables ทั้งหมดจากไฟล์ .env มาใช้งานใน container นี้
    env_file:
      - .env
    depends_on:
      # กำหนดให้ api service เริ่มทำงานหลังจาก postgres และ minio พร้อมใช้งานแล้ว
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      # Map พอร์ตของ api service ใน container ออกมาที่เครื่องเรา
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  db_data:
  minio_data:

